RACK_DIR ?= ../Rack-SDK

SLUG = Dryer
VERSION = 2.0.0

FLAGS += -std=c++14

SOURCES += src/plugin.cpp
SOURCES += src/Dryer.cpp

DISTRIBUTABLES += res
DISTRIBUTABLES += $(wildcard LICENSE*)

include $(RACK_DIR)/plugin.mk
